### ISSUE TITLE
'getent_passwd' is undefined

### ISSUE THREAD

**Issue by z00m1n** [debops/ansible-bootstrap#38]
I'm running the [example playbook](https://docs.debops.org/en/latest/ansible/roles/ansible-bootstrap/docs/getting-started.html#example-playbook) using a command similar to

    ansible-playbook ./bootstrap.yml --check --limit my-vm --tags role::bootstrap:admin --user ubuntu --private-key ~/.ssh/my_key

and I get an error message (wrapped for readability)

	PLAY [Bootstrap Python support] ************************************************

	PLAY [Bootstrap host for Ansible management] ***********************************

	TASK [setup] *******************************************************************
	ok: [my-vm]

	TASK [debops.bootstrap : Gather information about existing home directories] ***

	TASK [debops.bootstrap : Create required system groups] ************************
	ok: [my-vm] => (item=adm)
	ok: [my-vm] => (item=sudo)

	TASK [debops.bootstrap : Create admin accounts] ********************************
	fatal: [my-vm]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value,
	which appears to include a variable that is undefined. The error was: 'getent_passwd' is
	undefined\n\nThe error appears to have been in
	'/usr/local/etc/ansible/roles/debops.bootstrap/tasks/admin_accounts.yml': line 16, column 3,
	but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending
	line appears to be:\n\n\n- name: Create admin accounts\n  ^ here\n"}
        [...]

	PLAY RECAP *********************************************************************
	my-vm          : ok=2    changed=0    unreachable=0    failed=1   

I feel this is somewhat similar to #34, but explicitely setting `bootstrap__admin` to `True` does not fix the issue. The `my-vm` remote system being set up is an OpenStack Ubuntu 16.04 system trimmed of anything not essential.

Is this a bug in DebOps or am I doing anything wrong ? How can I get this to work ?

**Comment by drybjed** [comment]
Looks like [this task](https://github.com/debops/ansible-bootstrap/blob/master/tasks/main.yml#L33-L36) needs to have the `role::bootstrap:admin` tag to be included with other tasks when this tag is used.

It's definitely a `debops.bootstrap` bug. If you want, you can add the tag to the task I pointed out, and after checking if that works, make a PR with the fix.

**Comment by z00m1n** [comment]
see #39

**Comment by drybjed** [comment]
Thanks, merged.
