### ISSUE TITLE
Preventing bootstrap to add an entry to /etc/hosts but still setting the hostname

### ISSUE THREAD

**Issue by tonin** [debops/ansible-bootstrap#52]
I think it would be good to have a bootstrap variable to tell debops to not add a 127.0.1.1 entry to the `/etc/hosts` file.  In some cases, for example on private networks without any DNS, you rely on the content of the `/etc/hosts` file and the 127.0.1.1 address gets in the way.  Still you want to be able to set the hostname of any debops managed machine.

My current workaround for that is to have a `lineinfile` task with `state: 'absent'` in my roles, which is not ideal.

**Comment by drybjed** [comment]
What about the [`bootstrap__hostname_domain_config_enabled`](bootstrap__hostname_domain_config_enabled) variable? Can you try setting it to `False` and checking if that helps?

Keep in mind that the `bootstrap` playbook/role is not mandatory. If you have some other method to prepare a host to be managed by Ansible, like PXE preseeding, `cloud-init` or LXC templates, then you can do all your preparation there and skip `debops.bootstrap` role entirely.

**Comment by tonin** [comment]
Yes, that's another workaround. My use case is that I'm running different VM out of different cloud infrastructures and would like to come up with a common setup that would work with vanilla OS images.

The `bootstrap__hostname_domain_config_enabled` is too strong in the way that it completely disable hostname management.  I'd like something just for not touching the `/etc/hosts` file.

**Comment by drybjed** [comment]
I see. OK, I guess we can add something like this, say:
```yaml
bootstrap__etc_hosts: True/False
```
Do you want to write a PR? If so, please do it against the [DebOps monorepo](https://github.com/debops/debops/).

**Comment by tonin** [comment]
Sure, I'll take a shot at it.
