### ISSUE TITLE
Error for 'sudo' base package

### ISSUE THREAD

**Issue by mbarcia** [debops/ansible-bootstrap#6]
Hi!  I wanted to file an error report for debops.bootstrap, since it also happened to me before, working with another debops role. Misa thinks there may be an issue with the apt module.

```shell
failed: [local.example.com] => (item=python,python-apt,python-pip,True,lsb-release) => {"failed": true, "item": "pytho
n,python-apt,python-pip,True,lsb-release"}
msg: No package matching 'True' is available

FATAL: all hosts have already failed -- aborting
```

As a workaround, I provided my own _bootstrap_base_packages_, removing sudo from the list. Hope this helps, thank you for your hard and excellent work with DebOps.

**Comment by mbarcia** [comment]
This issue will be fixed once the quotes from each element in the list are removed.

However, note that debops.apt (and possibly others) may mix this same list using with_flattened, which again runs the evaluation despite the lack of quotes (see https://github.com/debops/ansible-apt/blob/master/tasks/install_packages.yml#L27-L37).

But removing quotes from the list does fix this issue.

**Comment by ypid** [comment]
@mbarcia I never had that problem or #22. I would assume this is related to your Ansible controller setup? Is that something other than Debian GNU/Linux or Ubuntu GNU/Linux?

**Comment by mbarcia** [comment]
Hello @ypid, this has been fixed in the latest versions of Drupsible. I believe this was a problem known by @drybjed, and I _think_ it has been fixed in Ansible 2. Don't know the root cause though.
